<?php

return [

    'name'     => 'Eli Santiago López Mahecha',
    'role'     => 'Full Stack Developer',
    'tagline'  => 'Ingeniero de Sistemas con +3 años construyendo plataformas robustas con PHP/Laravel, recuperando proyectos abandonados y llevándolos a producción.',
    'email'    => 'eslopez.dev@gmail.com',
    'phone'    => '+57 301 425 5344',
    'location' => 'Bogotá, Colombia',
    'github'   => 'https://github.com/EliSLopezM',
    'linkedin' => 'https://www.linkedin.com/in/eli-santiago-lopez-mahecha-56a9861b9/',
    'cv_path'  => '/cv/CV_EliSantiago_Lopez.pdf',
    'available' => true,

    'stats' => [
        ['value' => '3+',  'label' => 'Años de experiencia'],
        ['value' => '6',   'label' => 'Proyectos en producción'],
        ['value' => '2',   'label' => 'Apps móviles publicadas'],
        ['value' => '100%', 'label' => 'Proyectos entregados'],
    ],

    'about' => [
        'paragraph1' => 'Soy Eli Santiago López, Ingeniero de Sistemas graduado de la Fundación Universitaria Los Libertadores (2024). Más de 3 años desarrollando software full stack en entornos reales y de producción.',
        'paragraph2' => 'Me especializo en <strong>PHP/Laravel</strong> para backend, <strong>Angular</strong> para frontend y arquitectura de servidores Linux con Docker. Mi diferencial: restaurar proyectos inconclusos o abandonados y llevarlos a producción funcional.',
        'paragraph3' => 'Actualmente soy el encargado del área tecnológica en <strong>Steps Consulting Corp</strong>, donde coordino requerimientos, defino arquitecturas y entrego productos a clientes directos.',
    ],

    'stack' => [
        [
            'name' => 'PHP',
            'type' => 'Lenguaje backend principal',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Laravel',
            'type' => 'Framework backend',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Angular',
            'type' => 'Framework frontend SPA',
            'category' => 'frontend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Python',
            'type' => 'Scripting de seguridad & automatización',
            'category' => 'ciberseguridad',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Node.js',
            'type' => 'Runtime JS backend',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Go',
            'type' => 'Microservicios & APIs',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Firebase',
            'type' => 'Auth & tiempo real',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" width="36" height="36">',
        ],
        [
            'name' => 'MySQL',
            'type' => 'Base de datos relacional',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'PostgreSQL',
            'type' => 'Base de datos relacional',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Docker',
            'type' => 'Contenedores & despliegue',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Android',
            'type' => 'Aplicaciones móviles',
            'category' => 'frontend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'iOS / Swift',
            'type' => 'Aplicaciones móviles Apple',
            'category' => 'frontend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Linux',
            'type' => 'Servidores & infraestructura',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'REST APIs',
            'type' => 'Diseño e integración',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'JavaScript',
            'type' => 'Lenguaje frontend',
            'level' => 'conocimiento',
            'category' => 'frontend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'WordPress',
            'type' => 'CMS & desarrollo web',
            'level' => 'conocimiento',
            'category' => 'frontend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Java',
            'type' => 'Backend empresarial',
            'level' => 'conocimiento',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'Spring Boot',
            'type' => 'Framework Java',
            'level' => 'conocimiento',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'MongoDB',
            'type' => 'Base de datos NoSQL',
            'level' => 'conocimiento',
            'category' => 'backend',
            'svg'  => '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg" width="36" height="36">',
        ],
        [
            'name' => 'SQL Server',
            'type' => 'Base de datos relacional',
            'category' => 'backend',
            'svg'  => '<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzNiAzNiI+PGVsbGlwc2UgY3g9IjE4IiBjeT0iOCIgcng9IjE0IiByeT0iNSIgZmlsbD0iI0NDMjkyNyIvPjxwYXRoIGQ9Ik00IDh2MjBjMCAyLjggNi4zIDUgMTQgNXMxNC0yLjIgMTQtNVY4IiBzdHJva2U9IiNDQzI5MjciIHN0cm9rZS13aWR0aD0iMi40IiBmaWxsPSJub25lIi8+PHBhdGggZD0iTTQgMTZjMCAyLjggNi4zIDUgMTQgNXMxNC0yLjIgMTQtNSIgc3Ryb2tlPSIjQ0MyOTI3IiBzdHJva2Utd2lkdGg9IjIuNCIgZmlsbD0ibm9uZSIvPjxwYXRoIGQ9Ik00IDI0YzAgMi44IDYuMyA1IDE0IDVzMTQtMi4yIDE0LTUiIHN0cm9rZT0iI0NDMjkyNyIgc3Ryb2tlLXdpZHRoPSIyLjQiIGZpbGw9Im5vbmUiLz48L3N2Zz4=" width="36" height="36">',
        ],
        [
            'name' => 'Claude / IA',
            'type' => 'Integración de modelos de IA',
            'category' => 'backend',
            'svg'  => '<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzNiAzNiI+PHBhdGggZD0iTTE4IDIgTDIwLjYgMTUuNCBMMzQgMTggTDIwLjYgMjAuNiBMMTggMzQgTDE1LjQgMjAuNiBMMiAxOCBMMTUuNCAxNS40IFoiIGZpbGw9IiNEOTc3NTciLz48L3N2Zz4=" width="36" height="36">',
        ],
        [
            'name' => 'Active Directory',
            'type' => 'Gestión de identidad e infraestructura',
            'category' => 'ciberseguridad',
            'svg'  => '<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzNiAzNiI+PHBhdGggZD0iTTE4IDMgTDMxIDh2OWMwIDktNiAxNC41LTEzIDE2LTctMS41LTEzLTctMTMtMTZWOHoiIGZpbGw9IiMwMDc4RDQiLz48cGF0aCBkPSJNMTIgMTguNWw0IDQgOC05IiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjIuNiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBmaWxsPSJub25lIi8+PC9zdmc+" width="36" height="36">',
        ],
    ],

    'projects' => [
        [
            'title'   => 'Timi — Plataforma Web & Apps Móviles',
            'company' => 'Steps Consulting Corp',
            'url'     => 'https://timiweb.com',
            'github'  => null,
            'image'   => 'timi.jpg',
            'tags'    => ['Laravel', 'Angular', 'Firebase', 'MySQL', 'Docker', 'iOS', 'Android'],
            'desc'    => 'Plataforma web construida desde cero con Laravel + panel de administración completo. Recuperé las apps Timi User y Timi Driver (iOS/Android) de un estado de abandono, actualizadas y publicadas nuevamente en Play Store y App Store. Integración con Firebase para autenticación en tiempo real.',
            'links'   => [
                ['label' => 'timiweb.com', 'url' => 'https://timiweb.com', 'featured' => true],
                ['label' => 'Play Store', 'url' => '#', 'featured' => false],
            ],
        ],
        [
            'title'   => 'DeUna Marketing — Reconstrucción Total',
            'company' => 'Steps Consulting Corp',
            'url'     => 'https://deunamarketing.com',
            'github'  => null,
            'image'   => 'deuna.jpg',
            'tags'    => ['Laravel', 'MySQL', 'Nginx', 'Linux', 'SEO'],
            'desc'    => 'Plataforma de marketing digital reconstruida desde los cimientos a partir de un proyecto obsoleto. Rediseño completo de arquitectura, base de datos y frontend. Módulos de gestión de contenido, formularios y optimización SEO técnica. Servidor Linux con Nginx configurado para producción.',
            'links'   => [
                ['label' => 'deunamarketing.com', 'url' => 'https://deunamarketing.com', 'featured' => true],
            ],
        ],
        [
            'title'   => 'Katapulta — Espacio Virtual UCSM',
            'company' => 'Universidad San Martín',
            'url'     => 'https://katapulta.sanmartin.edu.co',
            'github'  => null,
            'image'   => 'katapulta.jpg',
            'tags'    => ['Laravel', 'MySQL', 'PHP', 'Roles & Auth'],
            'desc'    => 'Espacio virtual educativo desarrollado desde cero para la Universidad San Martín. Gestión de usuarios, cursos y contenido académico. Autenticación segura con roles diferenciados: estudiante, docente y administrador, implementados con Laravel y MySQL.',
            'links'   => [
                ['label' => 'katapulta.sanmartin.edu.co', 'url' => 'https://katapulta.sanmartin.edu.co', 'featured' => true],
            ],
        ],
        [
            'title'   => 'EcologicAds — Actualización & Optimización',
            'company' => 'Proyecto externo',
            'url'     => 'https://ecologicads.com',
            'github'  => null,
            'image'   => 'ecologicads.jpg',
            'tags'    => ['PHP', 'MySQL', 'Linux', 'Cache', 'SQL Tuning'],
            'desc'    => 'Plataforma de publicidad ecológica actualizada y optimizada. Corrección de deuda técnica acumulada y modernización de arquitectura de base de datos. Mejoras de rendimiento mediante optimización de consultas SQL, implementación de caché y ajustes en servidor Linux.',
            'links'   => [
                ['label' => 'ecologicads.com', 'url' => 'https://ecologicads.com', 'featured' => true],
            ],
        ],
        [
            'title'   => 'Elso.club — Plataforma de Estudios en Salud',
            'company' => 'Steps Consulting Corp',
            'url'     => 'https://elso.club',
            'github'  => null,
            'image'   => 'elso-club.jpg',
            'tags'    => ['WordPress', 'LearnDash', 'BuddyBoss', 'PHP', 'MySQL'],
            'desc'    => 'Plataforma de estudios en línea enfocada en cursos de salud, construida sobre WordPress con LearnDash como LMS y el theme BuddyBoss para la capa de red social: perfiles, grupos y actividad entre estudiantes.',
            'links'   => [
                ['label' => 'elso.club', 'url' => 'https://elso.club', 'featured' => true],
            ],
        ],
        [
            'title'   => 'Steps Puerto Rico Corp — Integración API Outlook',
            'company' => 'Steps Puerto Rico Corp',
            'url'     => 'https://stepspuertoricocorp.com',
            'github'  => null,
            'image'   => 'stepspuertoricocorp.jpg',
            'tags'    => ['Laravel', 'Microsoft Graph API', 'Outlook', 'PHP', 'MySQL'],
            'desc'    => 'Sitio de presentación corporativa para Steps Puerto Rico Corp, empresa tecnológica, con incorporación de una API para la gestión de mensajes de correo de Outlook.',
            'links'   => [
                ['label' => 'stepspuertoricocorp.com', 'url' => 'https://stepspuertoricocorp.com', 'featured' => true],
            ],
        ],
    ],

    'ai_processes' => [
        [
            'title' => 'Automatización de procesos',
            'desc'  => 'Flujos de trabajo repetitivos resueltos con IA: desde procesamiento de datos hasta tareas administrativas que antes eran manuales.',
            'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>',
        ],
        [
            'title' => 'Pagos virtuales y métodos de pago',
            'desc'  => 'Integración de pasarelas de pago y flujos de cobro virtual, con validaciones y confirmaciones asistidas por IA.',
            'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>',
        ],
        [
            'title' => 'Notificaciones y correos automáticos',
            'desc'  => 'Envío de notificaciones y correos disparados por eventos del sistema, con contenido generado y filtrado mediante IA.',
            'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22 6 12 13 2 6"/></svg>',
        ],
        [
            'title' => 'Protocolos de seguridad',
            'desc'  => 'Implementación de protocolos de autenticación, cifrado y control de acceso, reforzados con validaciones inteligentes.',
            'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/></svg>',
        ],
        [
            'title' => 'Documentación de procesos con IA',
            'desc'  => 'Descripción y documentación de flujos y procesos técnicos generada y estructurada con apoyo de IA, para equipos y clientes.',
            'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>',
        ],
    ],

    'experience' => [
        [
            'period'  => '2022 — Presente',
            'role'    => 'Programador Full Stack & Encargado de Tecnología',
            'company' => 'Steps Consulting Corp · Remoto, Colombia',
            'current' => true,
            'items'   => [
                'Desarrollo de plataformas web completas desde cero con PHP/Laravel.',
                'Reactivación de apps móviles Timi User y Timi Driver (iOS & Android).',
                'Diseño de arquitectura de servidores Linux, MySQL/PostgreSQL y pipelines con Docker.',
                'Liderazgo técnico: coordinación de requerimientos y entregas con clientes directos.',
            ],
            'tags' => ['Laravel', 'Angular', 'Node.js', 'MySQL', 'Docker', 'Firebase', 'Linux'],
        ],
        [
            'period'  => '2024',
            'role'    => 'Ingeniero de Sistemas — Graduado',
            'company' => 'Fundación Universitaria Los Libertadores · Bogotá',
            'current' => false,
            'items'   => [
                'Grado en Ingeniería de Sistemas.',
                'Certificaciones y estudios complementarios verificables en LinkedIn.',
            ],
            'tags' => ['Educación'],
        ],
    ],

    'languages' => [
        ['name' => 'Español', 'level' => 'Nativo',            'pct' => 100],
        ['name' => 'Inglés',  'level' => 'Básico-Intermedio', 'pct' => 45],
    ],
    'certs' => [
        // ── Destacados ──
        [
            'title'    => 'Diploma de Grado — Ing. de Sistemas',
            'platform' => 'Los Libertadores',
            'year'     => '2024',
            'pdf'      => 'diploma-grado.pdf',
            'preview'  => 'diploma-grado.jpg',
            'category' => 'destacado',
        ],
        [
            'title'    => 'Auditor Interno ISO/IEC 27001:2022',
            'platform' => 'ICONTEC',
            'year'     => '2024',
            'pdf'      => 'iso-27001.pdf',
            'preview'  => 'iso-27001.jpg',
            'category' => 'destacado',
        ],
        [
            'title'    => 'Seminario Big Data Analytics',
            'platform' => 'Los Libertadores',
            'year'     => '2023',
            'pdf'      => 'big-data-analytics.pdf',
            'preview'  => 'big-data-analytics.png',
            'category' => 'destacado',
        ],
        // ── Cursos ──
        [
            'title'    => 'Curso de Git y GitHub',
            'platform' => 'Platzi',
            'year'     => '2025',
            'pdf'      => 'git-github.pdf',
            'preview'  => 'git-github.png',
            'category' => 'curso',
        ],
        [
            'title'    => 'Taller Ciberseguridad para Prevenir Ataques',
            'platform' => 'Platzi',
            'year'     => '2025',
            'pdf'      => 'ciberseguridad-ataques.pdf',
            'preview'  => 'ciberseguridad-ataques.png',
            'category' => 'curso',
        ],
        [
            'title'    => 'Seguridad y Privacidad Digital',
            'platform' => 'MinTIC',
            'year'     => '2024',
            'pdf'      => 'seguridad-privacidad.pdf',
            'preview'  => 'seguridad-privacidad.png',
            'category' => 'curso',
        ],
        [
            'title'    => 'Seguridad Digital',
            'platform' => 'MinTIC',
            'year'     => '2024',
            'pdf'      => 'seguridad-digital.pdf',
            'preview'  => 'seguridad-digital.png',
            'category' => 'curso',
        ],
        [
            'title'    => 'Curso de Testing Estático',
            'platform' => 'Código Facilito',
            'year'     => '2024',
            'pdf'      => 'testing-estatico.pdf',
            'preview'  => 'testing-estatico.png',
            'category' => 'curso',
        ],
        [
            'title'    => 'Curso Profesional de Go',
            'platform' => 'Código Facilito',
            'year'     => '2024',
            'pdf'      => 'golang-profesional.pdf',
            'preview'  => 'golang-profesional.png',
            'category' => 'curso',
        ],
        [
            'title'    => 'Bases de Datos — Generalidades y Gestión',
            'platform' => 'SENA',
            'year'     => '2021',
            'pdf'      => 'sena-bases-de-datos.pdf',
            'preview'  => 'sena-bases-de-datos.png',
            'category' => 'curso',
        ],
        [
            'title'    => 'Soporte Técnico — Mantenimiento de Equipos',
            'platform' => 'SENA',
            'year'     => '2021',
            'pdf'      => 'sena-soporte-tecnico.pdf',
            'preview'  => 'sena-soporte-tecnico.png',
            'category' => 'curso',
        ],
    ],

];